version: '2.4'
services:
  web:
    image: "wesmaster/moneygrip_web:latest"
    container_name: moneygrip_web
    ports:
     - "86:4200"
    depends_on:
     - api
     - db
    cpus: 0.5
    mem_limit: 1000m
  api:
    image: "wesmaster/moneygrip_api:latest"
    container_name: moneygrip_api
    ports:
     - "5000:80"
    depends_on:
     - db
    cpus: 0.5
    mem_limit: 100m 
  db:
    image: "wesmaster/moneygrip_db:latest"
    container_name: moneygrip_db
    expose:
     - "1433"
    volumes:
     - C:\MoneyGrip\database:C:\data
    cpus: 0.5
    mem_limit: 1000m